/* Generated by gen_tracer.py -- Lua 5.1 C API call tracer.
** Exports the Lua 5.1 API as lua5.1.dll; every call is logged and then
** forwarded to luacore.dll (the real implementation) in the same folder.
** Output: OutputDebugStringA (Sysinternals DebugView) and, if the
** environment variable LUATRACE_FILE is set, appended to that file.
** Set LUATRACE_OFF=1 to silence it. */
#include <windows.h>
#include <stdio.h>
#include <stdarg.h>
#include <string.h>
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"

#define TRBUF 2048
static unsigned long g_seq = 0;
static HMODULE g_core = NULL;
static FILE *g_file = NULL;
static int g_off = 0;

#define P(...) do { if (bn < TRBUF - 64) bn += _snprintf(buf + bn, TRBUF - 64 - bn, __VA_ARGS__); if (bn < 0 || bn > TRBUF - 64) bn = TRBUF - 64; } while (0)
#define EMIT() emit(buf, bn)
#define QS(s, n) bn = qs(buf, bn, (s), (n))
#define IDX(L, i) bn = tr_idx(buf, bn, (L), (i))
#define REGS(l) bn = regs(buf, bn, (l))
#define OPTS(l) bn = opts(buf, bn, (l))
#define SN(r) statusname(r)

static void emit(char *buf, int bn) {
  char line[TRBUF + 32];
  if (g_off) return;
  _snprintf(line, sizeof(line) - 2, "[luatrace] %.*s", bn, buf);
  line[sizeof(line) - 3] = 0;
  strcat(line, "\n");
  OutputDebugStringA(line);
  if (g_file) { fputs(line, g_file); fflush(g_file); }
}

static void tr_log(const char *fmt, ...) {
  char buf[TRBUF]; int bn;
  va_list ap; va_start(ap, fmt);
  bn = _vsnprintf(buf, TRBUF - 64, fmt, ap);
  va_end(ap);
  if (bn < 0 || bn > TRBUF - 64) bn = TRBUF - 64;
  emit(buf, bn);
}

static int qs(char *buf, int bn, const char *s, size_t n) {
  size_t i;
  if (s == NULL) { return bn + _snprintf(buf + bn, TRBUF - 64 - bn, "NULL"); }
  if (n == (size_t)-1) n = strlen(s);
  if (bn < TRBUF - 70) buf[bn++] = '"';
  for (i = 0; i < n && bn < TRBUF - 72; i++) {
    unsigned char c = (unsigned char)s[i];
    if (i >= 120) { memcpy(buf + bn, "...", 3); bn += 3; break; }
    if (c == '\n') { buf[bn++] = '\\'; buf[bn++] = 'n'; }
    else if (c == '"') { buf[bn++] = '\\'; buf[bn++] = '"'; }
    else if (c < 32 || c >= 127) bn += _snprintf(buf + bn, 8, "\\x%02x", c);
    else buf[bn++] = (char)c;
  }
  if (bn < TRBUF - 64) buf[bn++] = '"';
  return bn;
}
static __typeof__(&lua_newstate) p_lua_newstate;
static __typeof__(&lua_close) p_lua_close;
static __typeof__(&lua_newthread) p_lua_newthread;
static __typeof__(&lua_atpanic) p_lua_atpanic;
static __typeof__(&lua_gettop) p_lua_gettop;
static __typeof__(&lua_settop) p_lua_settop;
static __typeof__(&lua_pushvalue) p_lua_pushvalue;
static __typeof__(&lua_remove) p_lua_remove;
static __typeof__(&lua_insert) p_lua_insert;
static __typeof__(&lua_replace) p_lua_replace;
static __typeof__(&lua_checkstack) p_lua_checkstack;
static __typeof__(&lua_xmove) p_lua_xmove;
static __typeof__(&lua_isnumber) p_lua_isnumber;
static __typeof__(&lua_isstring) p_lua_isstring;
static __typeof__(&lua_iscfunction) p_lua_iscfunction;
static __typeof__(&lua_isuserdata) p_lua_isuserdata;
static __typeof__(&lua_type) p_lua_type;
static __typeof__(&lua_typename) p_lua_typename;
static __typeof__(&lua_equal) p_lua_equal;
static __typeof__(&lua_rawequal) p_lua_rawequal;
static __typeof__(&lua_lessthan) p_lua_lessthan;
static __typeof__(&lua_tonumber) p_lua_tonumber;
static __typeof__(&lua_tointeger) p_lua_tointeger;
static __typeof__(&lua_toboolean) p_lua_toboolean;
static __typeof__(&lua_tolstring) p_lua_tolstring;
static __typeof__(&lua_objlen) p_lua_objlen;
static __typeof__(&lua_tocfunction) p_lua_tocfunction;
static __typeof__(&lua_touserdata) p_lua_touserdata;
static __typeof__(&lua_tothread) p_lua_tothread;
static __typeof__(&lua_topointer) p_lua_topointer;
static __typeof__(&lua_pushnil) p_lua_pushnil;
static __typeof__(&lua_pushnumber) p_lua_pushnumber;
static __typeof__(&lua_pushinteger) p_lua_pushinteger;
static __typeof__(&lua_pushlstring) p_lua_pushlstring;
static __typeof__(&lua_pushstring) p_lua_pushstring;
static __typeof__(&lua_pushvfstring) p_lua_pushvfstring;
static __typeof__(&lua_pushfstring) p_lua_pushfstring;
static __typeof__(&lua_pushcclosure) p_lua_pushcclosure;
static __typeof__(&lua_pushboolean) p_lua_pushboolean;
static __typeof__(&lua_pushlightuserdata) p_lua_pushlightuserdata;
static __typeof__(&lua_pushthread) p_lua_pushthread;
static __typeof__(&lua_gettable) p_lua_gettable;
static __typeof__(&lua_getfield) p_lua_getfield;
static __typeof__(&lua_rawget) p_lua_rawget;
static __typeof__(&lua_rawgeti) p_lua_rawgeti;
static __typeof__(&lua_createtable) p_lua_createtable;
static __typeof__(&lua_newuserdata) p_lua_newuserdata;
static __typeof__(&lua_getmetatable) p_lua_getmetatable;
static __typeof__(&lua_getfenv) p_lua_getfenv;
static __typeof__(&lua_settable) p_lua_settable;
static __typeof__(&lua_setfield) p_lua_setfield;
static __typeof__(&lua_rawset) p_lua_rawset;
static __typeof__(&lua_rawseti) p_lua_rawseti;
static __typeof__(&lua_setmetatable) p_lua_setmetatable;
static __typeof__(&lua_setfenv) p_lua_setfenv;
static __typeof__(&lua_call) p_lua_call;
static __typeof__(&lua_pcall) p_lua_pcall;
static __typeof__(&lua_cpcall) p_lua_cpcall;
static __typeof__(&lua_load) p_lua_load;
static __typeof__(&lua_dump) p_lua_dump;
static __typeof__(&lua_yield) p_lua_yield;
static __typeof__(&lua_resume) p_lua_resume;
static __typeof__(&lua_status) p_lua_status;
static __typeof__(&lua_gc) p_lua_gc;
static __typeof__(&lua_error) p_lua_error;
static __typeof__(&lua_next) p_lua_next;
static __typeof__(&lua_concat) p_lua_concat;
static __typeof__(&lua_getallocf) p_lua_getallocf;
static __typeof__(&lua_setallocf) p_lua_setallocf;
static __typeof__(&lua_setlevel) p_lua_setlevel;
static __typeof__(&lua_getstack) p_lua_getstack;
static __typeof__(&lua_getinfo) p_lua_getinfo;
static __typeof__(&lua_getlocal) p_lua_getlocal;
static __typeof__(&lua_setlocal) p_lua_setlocal;
static __typeof__(&lua_getupvalue) p_lua_getupvalue;
static __typeof__(&lua_setupvalue) p_lua_setupvalue;
static __typeof__(&lua_sethook) p_lua_sethook;
static __typeof__(&lua_gethook) p_lua_gethook;
static __typeof__(&lua_gethookmask) p_lua_gethookmask;
static __typeof__(&lua_gethookcount) p_lua_gethookcount;
static __typeof__(&luaL_openlib) p_luaL_openlib;
static __typeof__(&luaL_register) p_luaL_register;
static __typeof__(&luaL_getmetafield) p_luaL_getmetafield;
static __typeof__(&luaL_callmeta) p_luaL_callmeta;
static __typeof__(&luaL_typerror) p_luaL_typerror;
static __typeof__(&luaL_argerror) p_luaL_argerror;
static __typeof__(&luaL_checklstring) p_luaL_checklstring;
static __typeof__(&luaL_optlstring) p_luaL_optlstring;
static __typeof__(&luaL_checknumber) p_luaL_checknumber;
static __typeof__(&luaL_optnumber) p_luaL_optnumber;
static __typeof__(&luaL_checkinteger) p_luaL_checkinteger;
static __typeof__(&luaL_optinteger) p_luaL_optinteger;
static __typeof__(&luaL_checkstack) p_luaL_checkstack;
static __typeof__(&luaL_checktype) p_luaL_checktype;
static __typeof__(&luaL_checkany) p_luaL_checkany;
static __typeof__(&luaL_newmetatable) p_luaL_newmetatable;
static __typeof__(&luaL_checkudata) p_luaL_checkudata;
static __typeof__(&luaL_where) p_luaL_where;
static __typeof__(&luaL_error) p_luaL_error;
static __typeof__(&luaL_checkoption) p_luaL_checkoption;
static __typeof__(&luaL_ref) p_luaL_ref;
static __typeof__(&luaL_unref) p_luaL_unref;
static __typeof__(&luaL_loadfile) p_luaL_loadfile;
static __typeof__(&luaL_loadbuffer) p_luaL_loadbuffer;
static __typeof__(&luaL_loadstring) p_luaL_loadstring;
static __typeof__(&luaL_newstate) p_luaL_newstate;
static __typeof__(&luaL_gsub) p_luaL_gsub;
static __typeof__(&luaL_findtable) p_luaL_findtable;
static __typeof__(&luaL_buffinit) p_luaL_buffinit;
static __typeof__(&luaL_prepbuffer) p_luaL_prepbuffer;
static __typeof__(&luaL_addlstring) p_luaL_addlstring;
static __typeof__(&luaL_addstring) p_luaL_addstring;
static __typeof__(&luaL_addvalue) p_luaL_addvalue;
static __typeof__(&luaL_pushresult) p_luaL_pushresult;
static __typeof__(&luaopen_base) p_luaopen_base;
static __typeof__(&luaopen_table) p_luaopen_table;
static __typeof__(&luaopen_io) p_luaopen_io;
static __typeof__(&luaopen_os) p_luaopen_os;
static __typeof__(&luaopen_string) p_luaopen_string;
static __typeof__(&luaopen_math) p_luaopen_math;
static __typeof__(&luaopen_debug) p_luaopen_debug;
static __typeof__(&luaopen_package) p_luaopen_package;
static __typeof__(&luaL_openlibs) p_luaL_openlibs;

static const char *statusname(int s) {
  switch (s) { case 0: return "OK"; case 1: return "YIELD"; case 2: return "ERRRUN";
    case 3: return "ERRSYNTAX"; case 4: return "ERRMEM"; case 5: return "ERRERR"; }
  return "?";
}

/* describe the value at an index: idx<type:value> */
static int tr_idx(char *buf, int bn, lua_State *L, int i) {
  int t;
  const char *pseudo = i == LUA_REGISTRYINDEX ? "REGISTRY" : i == LUA_GLOBALSINDEX ? "GLOBALS" :
                       i == LUA_ENVIRONINDEX ? "ENVIRON" : NULL;
  if (pseudo) bn += _snprintf(buf + bn, TRBUF - 64 - bn, "%s", pseudo);
  else if (i < LUA_GLOBALSINDEX) bn += _snprintf(buf + bn, TRBUF - 64 - bn, "upvalue(%d)", LUA_GLOBALSINDEX - i);
  else if (i != 0x7fffffff) bn += _snprintf(buf + bn, TRBUF - 64 - bn, "%d", i);
  if (i == 0x7fffffff) i = -1; /* value only, no index label */
  if (L == NULL || bn > TRBUF - 200) return bn;
  t = p_lua_type(L, i);
  switch (t) {
    case LUA_TNONE: bn += _snprintf(buf + bn, TRBUF - 64 - bn, "<none>"); break;
    case LUA_TNIL: bn += _snprintf(buf + bn, TRBUF - 64 - bn, "<nil>"); break;
    case LUA_TBOOLEAN: bn += _snprintf(buf + bn, TRBUF - 64 - bn, "<bool:%s>", p_lua_toboolean(L, i) ? "true" : "false"); break;
    case LUA_TNUMBER: bn += _snprintf(buf + bn, TRBUF - 64 - bn, "<number:%.14g>", p_lua_tonumber(L, i)); break;
    case LUA_TSTRING: {
      size_t n; const char *s = p_lua_tolstring(L, i, &n);
      bn += _snprintf(buf + bn, TRBUF - 64 - bn, "<string:");
      bn = qs(buf, bn, s, n);
      bn += _snprintf(buf + bn, TRBUF - 64 - bn, ">");
      break;
    }
    default: bn += _snprintf(buf + bn, TRBUF - 64 - bn, "<%s>", p_lua_typename(L, t)); break;
  }
  return bn;
}

static int regs(char *buf, int bn, const luaL_Reg *l) {
  int n = 0;
  if (l == NULL) return bn + _snprintf(buf + bn, TRBUF - 64 - bn, "NULL");
  bn += _snprintf(buf + bn, TRBUF - 64 - bn, "{");
  for (; l->name && bn < TRBUF - 200; l++, n++)
    bn += _snprintf(buf + bn, TRBUF - 64 - bn, "%s%s", n ? "," : "", l->name);
  return bn + _snprintf(buf + bn, TRBUF - 64 - bn, "}");
}

static int opts(char *buf, int bn, const char *const *l) {
  int n = 0;
  if (l == NULL) return bn + _snprintf(buf + bn, TRBUF - 64 - bn, "NULL");
  bn += _snprintf(buf + bn, TRBUF - 64 - bn, "{");
  for (; *l && bn < TRBUF - 200; l++, n++)
    bn += _snprintf(buf + bn, TRBUF - 64 - bn, "%s%s", n ? "," : "", *l);
  return bn + _snprintf(buf + bn, TRBUF - 64 - bn, "}");
}

static FARPROC resolve(const char *name) {
  FARPROC f = GetProcAddress(g_core, name);
  if (f == NULL) tr_log("!!! luacore.dll does not export %s", name);
  return f;
}

static void load_core(void) {
  char path[MAX_PATH], *slash;
  HMODULE self = NULL;
  const char *env;
  if (g_core) return;
  env = getenv("LUATRACE_OFF");
  g_off = env && *env && *env != '0';
  env = getenv("LUATRACE_FILE");
  if (env && *env) g_file = fopen(env, "a");
  GetModuleHandleExA(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS | GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
                     (LPCSTR)&load_core, &self);
  GetModuleFileNameA(self, path, MAX_PATH);
  slash = strrchr(path, '\\');
  strcpy(slash ? slash + 1 : path, "luacore.dll");
  g_core = LoadLibraryA(path);
  if (g_core == NULL) {
    char msg[MAX_PATH + 64];
    _snprintf(msg, sizeof(msg), "luatrace: cannot load %s (error %lu)", path, GetLastError());
    OutputDebugStringA(msg);
    MessageBoxA(NULL, msg, "lua5.1.dll (trace)", MB_ICONERROR);
    ExitProcess(3);
  }
  tr_log("==== luatrace: forwarding to %s (pid %lu) ====", path, GetCurrentProcessId());
  p_lua_newstate = (__typeof__(p_lua_newstate))resolve("lua_newstate");
  p_lua_close = (__typeof__(p_lua_close))resolve("lua_close");
  p_lua_newthread = (__typeof__(p_lua_newthread))resolve("lua_newthread");
  p_lua_atpanic = (__typeof__(p_lua_atpanic))resolve("lua_atpanic");
  p_lua_gettop = (__typeof__(p_lua_gettop))resolve("lua_gettop");
  p_lua_settop = (__typeof__(p_lua_settop))resolve("lua_settop");
  p_lua_pushvalue = (__typeof__(p_lua_pushvalue))resolve("lua_pushvalue");
  p_lua_remove = (__typeof__(p_lua_remove))resolve("lua_remove");
  p_lua_insert = (__typeof__(p_lua_insert))resolve("lua_insert");
  p_lua_replace = (__typeof__(p_lua_replace))resolve("lua_replace");
  p_lua_checkstack = (__typeof__(p_lua_checkstack))resolve("lua_checkstack");
  p_lua_xmove = (__typeof__(p_lua_xmove))resolve("lua_xmove");
  p_lua_isnumber = (__typeof__(p_lua_isnumber))resolve("lua_isnumber");
  p_lua_isstring = (__typeof__(p_lua_isstring))resolve("lua_isstring");
  p_lua_iscfunction = (__typeof__(p_lua_iscfunction))resolve("lua_iscfunction");
  p_lua_isuserdata = (__typeof__(p_lua_isuserdata))resolve("lua_isuserdata");
  p_lua_type = (__typeof__(p_lua_type))resolve("lua_type");
  p_lua_typename = (__typeof__(p_lua_typename))resolve("lua_typename");
  p_lua_equal = (__typeof__(p_lua_equal))resolve("lua_equal");
  p_lua_rawequal = (__typeof__(p_lua_rawequal))resolve("lua_rawequal");
  p_lua_lessthan = (__typeof__(p_lua_lessthan))resolve("lua_lessthan");
  p_lua_tonumber = (__typeof__(p_lua_tonumber))resolve("lua_tonumber");
  p_lua_tointeger = (__typeof__(p_lua_tointeger))resolve("lua_tointeger");
  p_lua_toboolean = (__typeof__(p_lua_toboolean))resolve("lua_toboolean");
  p_lua_tolstring = (__typeof__(p_lua_tolstring))resolve("lua_tolstring");
  p_lua_objlen = (__typeof__(p_lua_objlen))resolve("lua_objlen");
  p_lua_tocfunction = (__typeof__(p_lua_tocfunction))resolve("lua_tocfunction");
  p_lua_touserdata = (__typeof__(p_lua_touserdata))resolve("lua_touserdata");
  p_lua_tothread = (__typeof__(p_lua_tothread))resolve("lua_tothread");
  p_lua_topointer = (__typeof__(p_lua_topointer))resolve("lua_topointer");
  p_lua_pushnil = (__typeof__(p_lua_pushnil))resolve("lua_pushnil");
  p_lua_pushnumber = (__typeof__(p_lua_pushnumber))resolve("lua_pushnumber");
  p_lua_pushinteger = (__typeof__(p_lua_pushinteger))resolve("lua_pushinteger");
  p_lua_pushlstring = (__typeof__(p_lua_pushlstring))resolve("lua_pushlstring");
  p_lua_pushstring = (__typeof__(p_lua_pushstring))resolve("lua_pushstring");
  p_lua_pushvfstring = (__typeof__(p_lua_pushvfstring))resolve("lua_pushvfstring");
  p_lua_pushfstring = (__typeof__(p_lua_pushfstring))resolve("lua_pushfstring");
  p_lua_pushcclosure = (__typeof__(p_lua_pushcclosure))resolve("lua_pushcclosure");
  p_lua_pushboolean = (__typeof__(p_lua_pushboolean))resolve("lua_pushboolean");
  p_lua_pushlightuserdata = (__typeof__(p_lua_pushlightuserdata))resolve("lua_pushlightuserdata");
  p_lua_pushthread = (__typeof__(p_lua_pushthread))resolve("lua_pushthread");
  p_lua_gettable = (__typeof__(p_lua_gettable))resolve("lua_gettable");
  p_lua_getfield = (__typeof__(p_lua_getfield))resolve("lua_getfield");
  p_lua_rawget = (__typeof__(p_lua_rawget))resolve("lua_rawget");
  p_lua_rawgeti = (__typeof__(p_lua_rawgeti))resolve("lua_rawgeti");
  p_lua_createtable = (__typeof__(p_lua_createtable))resolve("lua_createtable");
  p_lua_newuserdata = (__typeof__(p_lua_newuserdata))resolve("lua_newuserdata");
  p_lua_getmetatable = (__typeof__(p_lua_getmetatable))resolve("lua_getmetatable");
  p_lua_getfenv = (__typeof__(p_lua_getfenv))resolve("lua_getfenv");
  p_lua_settable = (__typeof__(p_lua_settable))resolve("lua_settable");
  p_lua_setfield = (__typeof__(p_lua_setfield))resolve("lua_setfield");
  p_lua_rawset = (__typeof__(p_lua_rawset))resolve("lua_rawset");
  p_lua_rawseti = (__typeof__(p_lua_rawseti))resolve("lua_rawseti");
  p_lua_setmetatable = (__typeof__(p_lua_setmetatable))resolve("lua_setmetatable");
  p_lua_setfenv = (__typeof__(p_lua_setfenv))resolve("lua_setfenv");
  p_lua_call = (__typeof__(p_lua_call))resolve("lua_call");
  p_lua_pcall = (__typeof__(p_lua_pcall))resolve("lua_pcall");
  p_lua_cpcall = (__typeof__(p_lua_cpcall))resolve("lua_cpcall");
  p_lua_load = (__typeof__(p_lua_load))resolve("lua_load");
  p_lua_dump = (__typeof__(p_lua_dump))resolve("lua_dump");
  p_lua_yield = (__typeof__(p_lua_yield))resolve("lua_yield");
  p_lua_resume = (__typeof__(p_lua_resume))resolve("lua_resume");
  p_lua_status = (__typeof__(p_lua_status))resolve("lua_status");
  p_lua_gc = (__typeof__(p_lua_gc))resolve("lua_gc");
  p_lua_error = (__typeof__(p_lua_error))resolve("lua_error");
  p_lua_next = (__typeof__(p_lua_next))resolve("lua_next");
  p_lua_concat = (__typeof__(p_lua_concat))resolve("lua_concat");
  p_lua_getallocf = (__typeof__(p_lua_getallocf))resolve("lua_getallocf");
  p_lua_setallocf = (__typeof__(p_lua_setallocf))resolve("lua_setallocf");
  p_lua_setlevel = (__typeof__(p_lua_setlevel))resolve("lua_setlevel");
  p_lua_getstack = (__typeof__(p_lua_getstack))resolve("lua_getstack");
  p_lua_getinfo = (__typeof__(p_lua_getinfo))resolve("lua_getinfo");
  p_lua_getlocal = (__typeof__(p_lua_getlocal))resolve("lua_getlocal");
  p_lua_setlocal = (__typeof__(p_lua_setlocal))resolve("lua_setlocal");
  p_lua_getupvalue = (__typeof__(p_lua_getupvalue))resolve("lua_getupvalue");
  p_lua_setupvalue = (__typeof__(p_lua_setupvalue))resolve("lua_setupvalue");
  p_lua_sethook = (__typeof__(p_lua_sethook))resolve("lua_sethook");
  p_lua_gethook = (__typeof__(p_lua_gethook))resolve("lua_gethook");
  p_lua_gethookmask = (__typeof__(p_lua_gethookmask))resolve("lua_gethookmask");
  p_lua_gethookcount = (__typeof__(p_lua_gethookcount))resolve("lua_gethookcount");
  p_luaL_openlib = (__typeof__(p_luaL_openlib))resolve("luaL_openlib");
  p_luaL_register = (__typeof__(p_luaL_register))resolve("luaL_register");
  p_luaL_getmetafield = (__typeof__(p_luaL_getmetafield))resolve("luaL_getmetafield");
  p_luaL_callmeta = (__typeof__(p_luaL_callmeta))resolve("luaL_callmeta");
  p_luaL_typerror = (__typeof__(p_luaL_typerror))resolve("luaL_typerror");
  p_luaL_argerror = (__typeof__(p_luaL_argerror))resolve("luaL_argerror");
  p_luaL_checklstring = (__typeof__(p_luaL_checklstring))resolve("luaL_checklstring");
  p_luaL_optlstring = (__typeof__(p_luaL_optlstring))resolve("luaL_optlstring");
  p_luaL_checknumber = (__typeof__(p_luaL_checknumber))resolve("luaL_checknumber");
  p_luaL_optnumber = (__typeof__(p_luaL_optnumber))resolve("luaL_optnumber");
  p_luaL_checkinteger = (__typeof__(p_luaL_checkinteger))resolve("luaL_checkinteger");
  p_luaL_optinteger = (__typeof__(p_luaL_optinteger))resolve("luaL_optinteger");
  p_luaL_checkstack = (__typeof__(p_luaL_checkstack))resolve("luaL_checkstack");
  p_luaL_checktype = (__typeof__(p_luaL_checktype))resolve("luaL_checktype");
  p_luaL_checkany = (__typeof__(p_luaL_checkany))resolve("luaL_checkany");
  p_luaL_newmetatable = (__typeof__(p_luaL_newmetatable))resolve("luaL_newmetatable");
  p_luaL_checkudata = (__typeof__(p_luaL_checkudata))resolve("luaL_checkudata");
  p_luaL_where = (__typeof__(p_luaL_where))resolve("luaL_where");
  p_luaL_error = (__typeof__(p_luaL_error))resolve("luaL_error");
  p_luaL_checkoption = (__typeof__(p_luaL_checkoption))resolve("luaL_checkoption");
  p_luaL_ref = (__typeof__(p_luaL_ref))resolve("luaL_ref");
  p_luaL_unref = (__typeof__(p_luaL_unref))resolve("luaL_unref");
  p_luaL_loadfile = (__typeof__(p_luaL_loadfile))resolve("luaL_loadfile");
  p_luaL_loadbuffer = (__typeof__(p_luaL_loadbuffer))resolve("luaL_loadbuffer");
  p_luaL_loadstring = (__typeof__(p_luaL_loadstring))resolve("luaL_loadstring");
  p_luaL_newstate = (__typeof__(p_luaL_newstate))resolve("luaL_newstate");
  p_luaL_gsub = (__typeof__(p_luaL_gsub))resolve("luaL_gsub");
  p_luaL_findtable = (__typeof__(p_luaL_findtable))resolve("luaL_findtable");
  p_luaL_buffinit = (__typeof__(p_luaL_buffinit))resolve("luaL_buffinit");
  p_luaL_prepbuffer = (__typeof__(p_luaL_prepbuffer))resolve("luaL_prepbuffer");
  p_luaL_addlstring = (__typeof__(p_luaL_addlstring))resolve("luaL_addlstring");
  p_luaL_addstring = (__typeof__(p_luaL_addstring))resolve("luaL_addstring");
  p_luaL_addvalue = (__typeof__(p_luaL_addvalue))resolve("luaL_addvalue");
  p_luaL_pushresult = (__typeof__(p_luaL_pushresult))resolve("luaL_pushresult");
  p_luaopen_base = (__typeof__(p_luaopen_base))resolve("luaopen_base");
  p_luaopen_table = (__typeof__(p_luaopen_table))resolve("luaopen_table");
  p_luaopen_io = (__typeof__(p_luaopen_io))resolve("luaopen_io");
  p_luaopen_os = (__typeof__(p_luaopen_os))resolve("luaopen_os");
  p_luaopen_string = (__typeof__(p_luaopen_string))resolve("luaopen_string");
  p_luaopen_math = (__typeof__(p_luaopen_math))resolve("luaopen_math");
  p_luaopen_debug = (__typeof__(p_luaopen_debug))resolve("luaopen_debug");
  p_luaopen_package = (__typeof__(p_luaopen_package))resolve("luaopen_package");
  p_luaL_openlibs = (__typeof__(p_luaL_openlibs))resolve("luaL_openlibs");
}

BOOL WINAPI DllMain(HINSTANCE h, DWORD reason, LPVOID r) {
  (void)h; (void)r;
  if (reason == DLL_PROCESS_DETACH) {
    tr_log("==== luatrace: lua5.1.dll unloading (process exit or FreeLibrary) ====");
    if (g_file) fflush(g_file);
  }
  return TRUE;
}


/* ---- optional Lua-level tracing (LUATRACE_LUA=1 calls, =2 calls+lines) ---- */
static int g_lua_level = -1;

static void tr_hook(lua_State *L, lua_Debug *ar) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  lua_Debug caller;
  if (ar->event == LUA_HOOKLINE) {
    if (!p_lua_getinfo(L, "Sl", ar)) return;
    P("#%lu LUA line %s:%d", seq, ar->short_src, ar->currentline);
    EMIT();
    return;
  }
  if (ar->event != LUA_HOOKCALL) return;
  if (!p_lua_getinfo(L, "nSl", ar)) return;
  P("#%lu LUA call %s", seq, ar->name ? ar->name : "?");
  if (ar->what && strcmp(ar->what, "C") == 0) {
    /* C function: show its first two arguments */
    int i;
    P("(");
    for (i = 1; i <= 2; i++) {
      const char *nm = p_lua_getlocal(L, ar, i);
      if (nm == NULL) break;
      if (i > 1) P(", ");
      IDX(L, 0x7fffffff);
      p_lua_settop(L, -2);
    }
    P(") [C]");
  } else {
    P(" [%s %s:%d]", ar->what ? ar->what : "?", ar->short_src, ar->linedefined);
  }
  if (p_lua_getstack(L, 1, &caller) && p_lua_getinfo(L, "Sl", &caller) && caller.currentline > 0)
    P(" from %s:%d", caller.short_src, caller.currentline);
  EMIT();
}

static void install_hook(lua_State *L) {
  const char *env;
  if (L == NULL) return;
  if (g_lua_level < 0) {
    env = getenv("LUATRACE_LUA");
    g_lua_level = (env && *env) ? atoi(env) : 0;
  }
  if (g_lua_level <= 0 || g_off) return;
  p_lua_sethook(L, tr_hook, g_lua_level >= 2 ? (LUA_MASKCALL | LUA_MASKLINE) : LUA_MASKCALL, 0);
  tr_log("==== luatrace: Lua-level tracing enabled (level %d) on L=%p ====", g_lua_level, (void *)L);
}

/* ---- hand-written wrappers (varargs / non-returning) ---- */

const char *tr_lua_pushvfstring(lua_State *L, const char *fmt, va_list argp) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  const char *r;
  load_core();
  P("#%lu > lua_pushvfstring(L=%p, fmt=", seq, (void*)L); QS(fmt, (size_t)-1); P(") top=%d", p_lua_gettop(L)); EMIT();
  r = p_lua_pushvfstring(L, fmt, argp);
  bn = 0; P("#%lu < lua_pushvfstring = ", seq); QS(r, (size_t)-1); P(" top=%d", p_lua_gettop(L)); EMIT();
  return r;
}

const char *tr_lua_pushfstring(lua_State *L, const char *fmt, ...) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  const char *r; va_list ap;
  load_core();
  P("#%lu > lua_pushfstring(L=%p, fmt=", seq, (void*)L); QS(fmt, (size_t)-1); P(") top=%d", p_lua_gettop(L)); EMIT();
  va_start(ap, fmt);
  r = p_lua_pushvfstring(L, fmt, ap);
  va_end(ap);
  bn = 0; P("#%lu < lua_pushfstring = ", seq); QS(r, (size_t)-1); P(" top=%d", p_lua_gettop(L)); EMIT();
  return r;
}

int tr_luaL_error(lua_State *L, const char *fmt, ...) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  va_list ap;
  load_core();
  /* same as lauxlib.c: luaL_where(L, 1) .. formatted message, then lua_error */
  p_luaL_where(L, 1);
  va_start(ap, fmt);
  p_lua_pushvfstring(L, fmt, ap);
  va_end(ap);
  p_lua_concat(L, 2);
  P("#%lu > luaL_error(L=%p) msg=", seq, (void*)L); IDX(L, -1); P(" top=%d  (raises, does not return)", p_lua_gettop(L)); EMIT();
  return p_lua_error(L);
}

int tr_lua_error(lua_State *L) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  load_core();
  P("#%lu > lua_error(L=%p) value=", seq, (void*)L); IDX(L, -1); P(" top=%d  (raises, does not return)", p_lua_gettop(L)); EMIT();
  return p_lua_error(L);
}

/* ---- PUC-Rio internal functions: logged, then forwarded to luacore.dll ---- */
static const char *g_internal_names[] = {"luaA_pushobject","luaC_barrierback","luaC_barrierf","luaC_callGCTM","luaC_freeall","luaC_fullgc","luaC_link","luaC_linkupval","luaC_separateudata","luaC_step","luaD_call","luaD_callhook","luaD_growstack","luaD_poscall","luaD_precall","luaD_protectedparser","luaD_rawrunprotected","luaD_reallocCI","luaD_reallocstack","luaD_seterrorobj","luaD_throw","luaE_freethread","luaE_newthread","luaF_close","luaF_findupval","luaF_freeclosure","luaF_freeproto","luaF_freeupval","luaF_newCclosure","luaF_newLclosure","luaF_newproto","luaF_newupval","luaG_checkcode","luaG_checkopenop","luaG_concaterror","luaG_errormsg","luaG_runerror","luaH_free","luaH_get","luaH_getn","luaH_getnum","luaH_getstr","luaH_isdummy","luaH_mainposition","luaH_new","luaH_next","luaH_resizearray","luaH_set","luaH_setnum","luaH_setstr","luaK_checkstack","luaK_codeABC","luaK_codeABx","luaK_concat","luaK_dischargevars","luaK_exp2RK","luaK_exp2anyreg","luaK_exp2nextreg","luaK_exp2val","luaK_fixline","luaK_getlabel","luaK_goiftrue","luaK_indexed","luaK_infix","luaK_jump","luaK_nil","luaK_numberK","luaK_patchlist","luaK_patchtohere","luaK_posfix","luaK_prefix","luaK_reserveregs","luaK_ret","luaK_self","luaK_setlist","luaK_setoneret","luaK_setreturns","luaK_storevar","luaK_stringK","luaM_toobig","luaO_chunkid","luaO_fb2int","luaO_int2fb","luaO_log2","luaO_pushfstring","luaO_rawequalObj","luaO_str2d","luaS_newlstr","luaS_newudata","luaS_resize","luaT_gettm","luaT_init","luaU_dump","luaU_header","luaU_print","luaU_undump","luaV_concat","luaV_equalval","luaV_execute","luaV_lessthan","luaV_tonumber","luaV_tostring","luaX_init","luaX_lexerror","luaX_lookahead","luaX_newstring","luaX_next","luaX_syntaxerror","luaX_token2str","luaZ_fill","luaZ_lookahead","luaZ_openspace","luaZ_read"};
static void *g_internal_ptr[113];
static unsigned g_internal_hits[113];

void *tr_internal_hit(int i) {
  load_core();
  if (g_internal_ptr[i] == NULL) g_internal_ptr[i] = (void *)GetProcAddress(g_core, g_internal_names[i]);
  g_internal_hits[i]++;
  if (g_internal_hits[i] <= 5 || (g_internal_hits[i] & (g_internal_hits[i] - 1)) == 0)
    tr_log("#%lu !!! INTERNAL %s called (PUC-Rio private function, hit #%u) -> %s", ++g_seq,
           g_internal_names[i], g_internal_hits[i], g_internal_ptr[i] ? "forwarded to luacore.dll" : "MISSING in luacore.dll");
  if (g_internal_ptr[i] == NULL) {
    char msg[256];
    _snprintf(msg, sizeof(msg), "A module called the PUC-Rio internal function %s, which luacore.dll does not provide. The process will exit.", g_internal_names[i]);
    tr_log("!!! FATAL: %s", msg);
    MessageBoxA(NULL, msg, "lua5.1.dll (trace)", MB_ICONERROR);
    ExitProcess(4);
  }
  return g_internal_ptr[i];
}

/* ---- generated wrappers ---- */

lua_State * tr_lua_newstate(lua_Alloc f, void *ud) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  lua_State *L = NULL;
  (void)L;
  load_core();
  P("#%lu > lua_newstate(", seq);
  P("f=%p", (void*)f);
  P(", ");
  P("ud=%p", (void*)ud);
  P(")");
  EMIT();
  lua_State * rv = p_lua_newstate(f, ud);
  install_hook(rv);
  bn = 0; P("#%lu < lua_newstate", seq);
  P(" = %p", (void*)rv);
  EMIT();
  return rv;
}

void tr_lua_close(lua_State *L) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_close(", seq);
  P("L=%p", (void*)L);
  P(")");
  EMIT();
  p_lua_close(L);
  fflush(NULL); /* do not lose buffered print/io.write output */
  bn = 0; P("#%lu < lua_close (C stdio streams flushed)", seq); EMIT();
}

lua_State * tr_lua_newthread(lua_State *L) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_newthread(", seq);
  P("L=%p", (void*)L);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  lua_State * rv = p_lua_newthread(L);
  bn = 0; P("#%lu < lua_newthread", seq);
  P(" = %p", (void*)rv);
  EMIT();
  return rv;
}

lua_CFunction tr_lua_atpanic(lua_State *L, lua_CFunction panicf) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_atpanic(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("panicf=%p", (void*)panicf);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  lua_CFunction rv = p_lua_atpanic(L, panicf);
  bn = 0; P("#%lu < lua_atpanic", seq);
  P(" = %p", (void*)rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

int tr_lua_gettop(lua_State *L) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_gettop(", seq);
  P("L=%p", (void*)L);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_lua_gettop(L);
  bn = 0; P("#%lu < lua_gettop", seq);
  P(" = %d", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

void tr_lua_settop(lua_State *L, int idx) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_settop(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("idx=%d", idx);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  p_lua_settop(L, idx);
  bn = 0; P("#%lu < lua_settop", seq);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
}

void tr_lua_pushvalue(lua_State *L, int idx) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_pushvalue(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("idx="); IDX(L, idx);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  p_lua_pushvalue(L, idx);
  bn = 0; P("#%lu < lua_pushvalue", seq);
  P(" -> "); IDX(L, -1);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
}

void tr_lua_remove(lua_State *L, int idx) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_remove(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("idx="); IDX(L, idx);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  p_lua_remove(L, idx);
  bn = 0; P("#%lu < lua_remove", seq);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
}

void tr_lua_insert(lua_State *L, int idx) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_insert(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("idx="); IDX(L, idx);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  p_lua_insert(L, idx);
  bn = 0; P("#%lu < lua_insert", seq);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
}

void tr_lua_replace(lua_State *L, int idx) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_replace(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("idx="); IDX(L, idx);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  p_lua_replace(L, idx);
  bn = 0; P("#%lu < lua_replace", seq);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
}

int tr_lua_checkstack(lua_State *L, int sz) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_checkstack(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("sz=%d", sz);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_lua_checkstack(L, sz);
  bn = 0; P("#%lu < lua_checkstack", seq);
  P(" = %d", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

void tr_lua_xmove(lua_State *from, lua_State *to, int n) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  lua_State *L = NULL;
  (void)L;
  load_core();
  P("#%lu > lua_xmove(", seq);
  P("from=%p", (void*)from);
  P(", ");
  P("to=%p", (void*)to);
  P(", ");
  P("n=%d", n);
  P(")");
  EMIT();
  p_lua_xmove(from, to, n);
  bn = 0; P("#%lu < lua_xmove", seq);
  EMIT();
}

int tr_lua_isnumber(lua_State *L, int idx) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_isnumber(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("idx="); IDX(L, idx);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_lua_isnumber(L, idx);
  bn = 0; P("#%lu < lua_isnumber", seq);
  P(" = %d", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

int tr_lua_isstring(lua_State *L, int idx) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_isstring(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("idx="); IDX(L, idx);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_lua_isstring(L, idx);
  bn = 0; P("#%lu < lua_isstring", seq);
  P(" = %d", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

int tr_lua_iscfunction(lua_State *L, int idx) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_iscfunction(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("idx="); IDX(L, idx);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_lua_iscfunction(L, idx);
  bn = 0; P("#%lu < lua_iscfunction", seq);
  P(" = %d", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

int tr_lua_isuserdata(lua_State *L, int idx) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_isuserdata(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("idx="); IDX(L, idx);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_lua_isuserdata(L, idx);
  bn = 0; P("#%lu < lua_isuserdata", seq);
  P(" = %d", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

int tr_lua_type(lua_State *L, int idx) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_type(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("idx="); IDX(L, idx);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_lua_type(L, idx);
  bn = 0; P("#%lu < lua_type", seq);
  P(" = %d", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

const char * tr_lua_typename(lua_State *L, int tp) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_typename(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("tp=%d", tp);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  const char * rv = p_lua_typename(L, tp);
  bn = 0; P("#%lu < lua_typename", seq);
  P(" = "); QS(rv, (size_t)-1);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

int tr_lua_equal(lua_State *L, int idx1, int idx2) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_equal(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("idx1="); IDX(L, idx1);
  P(", ");
  P("idx2="); IDX(L, idx2);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_lua_equal(L, idx1, idx2);
  bn = 0; P("#%lu < lua_equal", seq);
  P(" = %d", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

int tr_lua_rawequal(lua_State *L, int idx1, int idx2) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_rawequal(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("idx1="); IDX(L, idx1);
  P(", ");
  P("idx2="); IDX(L, idx2);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_lua_rawequal(L, idx1, idx2);
  bn = 0; P("#%lu < lua_rawequal", seq);
  P(" = %d", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

int tr_lua_lessthan(lua_State *L, int idx1, int idx2) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_lessthan(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("idx1="); IDX(L, idx1);
  P(", ");
  P("idx2="); IDX(L, idx2);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_lua_lessthan(L, idx1, idx2);
  bn = 0; P("#%lu < lua_lessthan", seq);
  P(" = %d", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

lua_Number tr_lua_tonumber(lua_State *L, int idx) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_tonumber(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("idx="); IDX(L, idx);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  lua_Number rv = p_lua_tonumber(L, idx);
  bn = 0; P("#%lu < lua_tonumber", seq);
  P(" = %.14g", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

lua_Integer tr_lua_tointeger(lua_State *L, int idx) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_tointeger(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("idx="); IDX(L, idx);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  lua_Integer rv = p_lua_tointeger(L, idx);
  bn = 0; P("#%lu < lua_tointeger", seq);
  P(" = %lld", (long long)rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

int tr_lua_toboolean(lua_State *L, int idx) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_toboolean(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("idx="); IDX(L, idx);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_lua_toboolean(L, idx);
  bn = 0; P("#%lu < lua_toboolean", seq);
  P(" = %d", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

const char * tr_lua_tolstring(lua_State *L, int idx, size_t *len) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_tolstring(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("idx="); IDX(L, idx);
  P(", ");
  P("len=%p", (void*)len);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  const char * rv = p_lua_tolstring(L, idx, len);
  bn = 0; P("#%lu < lua_tolstring", seq);
  P(" = "); QS(rv, (size_t)-1);
  if (len) P(" len=%llu", (unsigned long long)*len);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

size_t tr_lua_objlen(lua_State *L, int idx) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_objlen(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("idx="); IDX(L, idx);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  size_t rv = p_lua_objlen(L, idx);
  bn = 0; P("#%lu < lua_objlen", seq);
  P(" = %llu", (unsigned long long)rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

lua_CFunction tr_lua_tocfunction(lua_State *L, int idx) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_tocfunction(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("idx="); IDX(L, idx);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  lua_CFunction rv = p_lua_tocfunction(L, idx);
  bn = 0; P("#%lu < lua_tocfunction", seq);
  P(" = %p", (void*)rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

void * tr_lua_touserdata(lua_State *L, int idx) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_touserdata(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("idx="); IDX(L, idx);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  void * rv = p_lua_touserdata(L, idx);
  bn = 0; P("#%lu < lua_touserdata", seq);
  P(" = %p", (void*)rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

lua_State * tr_lua_tothread(lua_State *L, int idx) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_tothread(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("idx="); IDX(L, idx);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  lua_State * rv = p_lua_tothread(L, idx);
  bn = 0; P("#%lu < lua_tothread", seq);
  P(" = %p", (void*)rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

const void * tr_lua_topointer(lua_State *L, int idx) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_topointer(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("idx="); IDX(L, idx);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  const void * rv = p_lua_topointer(L, idx);
  bn = 0; P("#%lu < lua_topointer", seq);
  P(" = %p", (void*)rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

void tr_lua_pushnil(lua_State *L) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_pushnil(", seq);
  P("L=%p", (void*)L);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  p_lua_pushnil(L);
  bn = 0; P("#%lu < lua_pushnil", seq);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
}

void tr_lua_pushnumber(lua_State *L, lua_Number n) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_pushnumber(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("n=%.14g", n);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  p_lua_pushnumber(L, n);
  bn = 0; P("#%lu < lua_pushnumber", seq);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
}

void tr_lua_pushinteger(lua_State *L, lua_Integer n) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_pushinteger(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("n=%lld", (long long)n);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  p_lua_pushinteger(L, n);
  bn = 0; P("#%lu < lua_pushinteger", seq);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
}

void tr_lua_pushlstring(lua_State *L, const char *s, size_t l) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_pushlstring(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("s="); QS(s, (size_t)-1);
  P(", ");
  P("l=%llu", (unsigned long long)l);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  p_lua_pushlstring(L, s, l);
  bn = 0; P("#%lu < lua_pushlstring", seq);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
}

void tr_lua_pushstring(lua_State *L, const char *s) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_pushstring(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("s="); QS(s, (size_t)-1);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  p_lua_pushstring(L, s);
  bn = 0; P("#%lu < lua_pushstring", seq);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
}

void tr_lua_pushcclosure(lua_State *L, lua_CFunction fn, int n) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_pushcclosure(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("fn=%p", (void*)fn);
  P(", ");
  P("n=%d", n);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  p_lua_pushcclosure(L, fn, n);
  bn = 0; P("#%lu < lua_pushcclosure", seq);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
}

void tr_lua_pushboolean(lua_State *L, int b) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_pushboolean(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("b=%d", b);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  p_lua_pushboolean(L, b);
  bn = 0; P("#%lu < lua_pushboolean", seq);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
}

void tr_lua_pushlightuserdata(lua_State *L, void *p) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_pushlightuserdata(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("p=%p", (void*)p);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  p_lua_pushlightuserdata(L, p);
  bn = 0; P("#%lu < lua_pushlightuserdata", seq);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
}

int tr_lua_pushthread(lua_State *L) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_pushthread(", seq);
  P("L=%p", (void*)L);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_lua_pushthread(L);
  bn = 0; P("#%lu < lua_pushthread", seq);
  P(" = %d", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

void tr_lua_gettable(lua_State *L, int idx) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_gettable(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("idx="); IDX(L, idx);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  p_lua_gettable(L, idx);
  bn = 0; P("#%lu < lua_gettable", seq);
  P(" -> "); IDX(L, -1);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
}

void tr_lua_getfield(lua_State *L, int idx, const char *k) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_getfield(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("idx="); IDX(L, idx);
  P(", ");
  P("k="); QS(k, (size_t)-1);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  p_lua_getfield(L, idx, k);
  bn = 0; P("#%lu < lua_getfield", seq);
  P(" -> "); IDX(L, -1);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
}

void tr_lua_rawget(lua_State *L, int idx) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_rawget(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("idx="); IDX(L, idx);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  p_lua_rawget(L, idx);
  bn = 0; P("#%lu < lua_rawget", seq);
  P(" -> "); IDX(L, -1);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
}

void tr_lua_rawgeti(lua_State *L, int idx, int n) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_rawgeti(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("idx="); IDX(L, idx);
  P(", ");
  P("n=%d", n);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  p_lua_rawgeti(L, idx, n);
  bn = 0; P("#%lu < lua_rawgeti", seq);
  P(" -> "); IDX(L, -1);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
}

void tr_lua_createtable(lua_State *L, int narr, int nrec) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_createtable(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("narr=%d", narr);
  P(", ");
  P("nrec=%d", nrec);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  p_lua_createtable(L, narr, nrec);
  bn = 0; P("#%lu < lua_createtable", seq);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
}

void * tr_lua_newuserdata(lua_State *L, size_t sz) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_newuserdata(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("sz=%llu", (unsigned long long)sz);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  void * rv = p_lua_newuserdata(L, sz);
  bn = 0; P("#%lu < lua_newuserdata", seq);
  P(" = %p", (void*)rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

int tr_lua_getmetatable(lua_State *L, int objindex) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_getmetatable(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("objindex="); IDX(L, objindex);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_lua_getmetatable(L, objindex);
  bn = 0; P("#%lu < lua_getmetatable", seq);
  P(" = %d", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

void tr_lua_getfenv(lua_State *L, int idx) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_getfenv(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("idx="); IDX(L, idx);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  p_lua_getfenv(L, idx);
  bn = 0; P("#%lu < lua_getfenv", seq);
  P(" -> "); IDX(L, -1);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
}

void tr_lua_settable(lua_State *L, int idx) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_settable(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("idx="); IDX(L, idx);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  p_lua_settable(L, idx);
  bn = 0; P("#%lu < lua_settable", seq);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
}

void tr_lua_setfield(lua_State *L, int idx, const char *k) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_setfield(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("idx="); IDX(L, idx);
  P(", ");
  P("k="); QS(k, (size_t)-1);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  p_lua_setfield(L, idx, k);
  bn = 0; P("#%lu < lua_setfield", seq);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
}

void tr_lua_rawset(lua_State *L, int idx) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_rawset(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("idx="); IDX(L, idx);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  p_lua_rawset(L, idx);
  bn = 0; P("#%lu < lua_rawset", seq);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
}

void tr_lua_rawseti(lua_State *L, int idx, int n) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_rawseti(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("idx="); IDX(L, idx);
  P(", ");
  P("n=%d", n);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  p_lua_rawseti(L, idx, n);
  bn = 0; P("#%lu < lua_rawseti", seq);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
}

int tr_lua_setmetatable(lua_State *L, int objindex) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_setmetatable(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("objindex="); IDX(L, objindex);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_lua_setmetatable(L, objindex);
  bn = 0; P("#%lu < lua_setmetatable", seq);
  P(" = %d", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

int tr_lua_setfenv(lua_State *L, int idx) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_setfenv(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("idx="); IDX(L, idx);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_lua_setfenv(L, idx);
  bn = 0; P("#%lu < lua_setfenv", seq);
  P(" = %d", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

void tr_lua_call(lua_State *L, int nargs, int nresults) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_call(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("nargs=%d", nargs);
  P(", ");
  P("nresults=%d", nresults);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  P(" func="); IDX(L, -(nargs + 1));
  EMIT();
  p_lua_call(L, nargs, nresults);
  bn = 0; P("#%lu < lua_call", seq);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
}

int tr_lua_pcall(lua_State *L, int nargs, int nresults, int errfunc) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_pcall(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("nargs=%d", nargs);
  P(", ");
  P("nresults=%d", nresults);
  P(", ");
  P("errfunc=%d", errfunc);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  P(" func="); IDX(L, -(nargs + 1));
  EMIT();
  int rv = p_lua_pcall(L, nargs, nresults, errfunc);
  bn = 0; P("#%lu < lua_pcall", seq);
  P(" = %d (%s)", rv, SN(rv)); if (rv != 0 && rv != 1) { P(" err="); IDX(L, -1); }
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

int tr_lua_cpcall(lua_State *L, lua_CFunction func, void *ud) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_cpcall(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("func=%p", (void*)func);
  P(", ");
  P("ud=%p", (void*)ud);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_lua_cpcall(L, func, ud);
  bn = 0; P("#%lu < lua_cpcall", seq);
  P(" = %d (%s)", rv, SN(rv)); if (rv != 0 && rv != 1) { P(" err="); IDX(L, -1); }
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

int tr_lua_load(lua_State *L, lua_Reader reader, void *dt, const char *chunkname) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_load(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("reader=%p", (void*)reader);
  P(", ");
  P("dt=%p", (void*)dt);
  P(", ");
  P("chunkname="); QS(chunkname, (size_t)-1);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_lua_load(L, reader, dt, chunkname);
  bn = 0; P("#%lu < lua_load", seq);
  P(" = %d (%s)", rv, SN(rv)); if (rv != 0 && rv != 1) { P(" err="); IDX(L, -1); }
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

int tr_lua_dump(lua_State *L, lua_Writer writer, void *data) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_dump(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("writer=%p", (void*)writer);
  P(", ");
  P("data=%p", (void*)data);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_lua_dump(L, writer, data);
  bn = 0; P("#%lu < lua_dump", seq);
  P(" = %d", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

int tr_lua_yield(lua_State *L, int nresults) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_yield(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("nresults=%d", nresults);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_lua_yield(L, nresults);
  bn = 0; P("#%lu < lua_yield", seq);
  P(" = %d", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

int tr_lua_resume(lua_State *L, int narg) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_resume(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("narg=%d", narg);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_lua_resume(L, narg);
  bn = 0; P("#%lu < lua_resume", seq);
  P(" = %d (%s)", rv, SN(rv)); if (rv != 0 && rv != 1) { P(" err="); IDX(L, -1); }
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

int tr_lua_status(lua_State *L) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_status(", seq);
  P("L=%p", (void*)L);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_lua_status(L);
  bn = 0; P("#%lu < lua_status", seq);
  P(" = %d", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

int tr_lua_gc(lua_State *L, int what, int data) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_gc(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("what=%d", what);
  P(", ");
  P("data=%d", data);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_lua_gc(L, what, data);
  bn = 0; P("#%lu < lua_gc", seq);
  P(" = %d", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

int tr_lua_next(lua_State *L, int idx) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_next(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("idx="); IDX(L, idx);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_lua_next(L, idx);
  bn = 0; P("#%lu < lua_next", seq);
  P(" = %d", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

void tr_lua_concat(lua_State *L, int n) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_concat(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("n=%d", n);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  p_lua_concat(L, n);
  bn = 0; P("#%lu < lua_concat", seq);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
}

lua_Alloc tr_lua_getallocf(lua_State *L, void **ud) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_getallocf(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("ud=%p", (void*)ud);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  lua_Alloc rv = p_lua_getallocf(L, ud);
  bn = 0; P("#%lu < lua_getallocf", seq);
  P(" = %p", (void*)rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

void tr_lua_setallocf(lua_State *L, lua_Alloc f, void *ud) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_setallocf(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("f=%p", (void*)f);
  P(", ");
  P("ud=%p", (void*)ud);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  p_lua_setallocf(L, f, ud);
  bn = 0; P("#%lu < lua_setallocf", seq);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
}

void tr_lua_setlevel(lua_State *from, lua_State *to) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  lua_State *L = NULL;
  (void)L;
  load_core();
  P("#%lu > lua_setlevel(", seq);
  P("from=%p", (void*)from);
  P(", ");
  P("to=%p", (void*)to);
  P(")");
  EMIT();
  p_lua_setlevel(from, to);
  bn = 0; P("#%lu < lua_setlevel", seq);
  EMIT();
}

int tr_lua_getstack(lua_State *L, int level, lua_Debug *ar) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_getstack(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("level=%d", level);
  P(", ");
  P("ar=%p", (void*)ar);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_lua_getstack(L, level, ar);
  bn = 0; P("#%lu < lua_getstack", seq);
  P(" = %d", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

int tr_lua_getinfo(lua_State *L, const char *what, lua_Debug *ar) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_getinfo(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("what="); QS(what, (size_t)-1);
  P(", ");
  P("ar=%p", (void*)ar);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_lua_getinfo(L, what, ar);
  bn = 0; P("#%lu < lua_getinfo", seq);
  P(" = %d", rv);
  if (rv && what && strchr(what, 'S')) { P(" src="); QS(ar->short_src, (size_t)-1); P(" what="); QS(ar->what, (size_t)-1); P(" linedefined=%d", ar->linedefined); }
  if (rv && what && strchr(what, 'l')) P(" currentline=%d", ar->currentline);
  if (rv && what && strchr(what, 'n')) { P(" name="); QS(ar->name, (size_t)-1); P(" namewhat="); QS(ar->namewhat, (size_t)-1); }
  if (rv && what && strchr(what, 'u')) P(" nups=%d", ar->nups);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

const char * tr_lua_getlocal(lua_State *L, const lua_Debug *ar, int n) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_getlocal(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("ar=%p", (void*)ar);
  P(", ");
  P("n=%d", n);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  const char * rv = p_lua_getlocal(L, ar, n);
  bn = 0; P("#%lu < lua_getlocal", seq);
  P(" = "); QS(rv, (size_t)-1);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

const char * tr_lua_setlocal(lua_State *L, const lua_Debug *ar, int n) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_setlocal(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("ar=%p", (void*)ar);
  P(", ");
  P("n=%d", n);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  const char * rv = p_lua_setlocal(L, ar, n);
  bn = 0; P("#%lu < lua_setlocal", seq);
  P(" = "); QS(rv, (size_t)-1);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

const char * tr_lua_getupvalue(lua_State *L, int funcindex, int n) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_getupvalue(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("funcindex="); IDX(L, funcindex);
  P(", ");
  P("n=%d", n);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  const char * rv = p_lua_getupvalue(L, funcindex, n);
  bn = 0; P("#%lu < lua_getupvalue", seq);
  P(" = "); QS(rv, (size_t)-1);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

const char * tr_lua_setupvalue(lua_State *L, int funcindex, int n) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_setupvalue(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("funcindex="); IDX(L, funcindex);
  P(", ");
  P("n=%d", n);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  const char * rv = p_lua_setupvalue(L, funcindex, n);
  bn = 0; P("#%lu < lua_setupvalue", seq);
  P(" = "); QS(rv, (size_t)-1);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

int tr_lua_sethook(lua_State *L, lua_Hook func, int mask, int count) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_sethook(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("func=%p", (void*)func);
  P(", ");
  P("mask=%d", mask);
  P(", ");
  P("count=%d", count);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_lua_sethook(L, func, mask, count);
  bn = 0; P("#%lu < lua_sethook", seq);
  P(" = %d", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

lua_Hook tr_lua_gethook(lua_State *L) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_gethook(", seq);
  P("L=%p", (void*)L);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  lua_Hook rv = p_lua_gethook(L);
  bn = 0; P("#%lu < lua_gethook", seq);
  P(" = %p", (void*)rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

int tr_lua_gethookmask(lua_State *L) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_gethookmask(", seq);
  P("L=%p", (void*)L);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_lua_gethookmask(L);
  bn = 0; P("#%lu < lua_gethookmask", seq);
  P(" = %d", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

int tr_lua_gethookcount(lua_State *L) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > lua_gethookcount(", seq);
  P("L=%p", (void*)L);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_lua_gethookcount(L);
  bn = 0; P("#%lu < lua_gethookcount", seq);
  P(" = %d", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

void tr_luaL_openlib(lua_State *L, const char *libname, const luaL_Reg *l, int nup) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > luaL_openlib(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("libname="); QS(libname, (size_t)-1);
  P(", ");
  P("l="); REGS(l);
  P(", ");
  P("nup=%d", nup);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  p_luaL_openlib(L, libname, l, nup);
  bn = 0; P("#%lu < luaL_openlib", seq);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
}

void tr_luaL_register(lua_State *L, const char *libname, const luaL_Reg *l) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > luaL_register(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("libname="); QS(libname, (size_t)-1);
  P(", ");
  P("l="); REGS(l);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  p_luaL_register(L, libname, l);
  bn = 0; P("#%lu < luaL_register", seq);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
}

int tr_luaL_getmetafield(lua_State *L, int obj, const char *e) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > luaL_getmetafield(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("obj="); IDX(L, obj);
  P(", ");
  P("e="); QS(e, (size_t)-1);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_luaL_getmetafield(L, obj, e);
  bn = 0; P("#%lu < luaL_getmetafield", seq);
  P(" = %d", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

int tr_luaL_callmeta(lua_State *L, int obj, const char *e) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > luaL_callmeta(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("obj="); IDX(L, obj);
  P(", ");
  P("e="); QS(e, (size_t)-1);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_luaL_callmeta(L, obj, e);
  bn = 0; P("#%lu < luaL_callmeta", seq);
  P(" = %d", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

int tr_luaL_typerror(lua_State *L, int narg, const char *tname) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > luaL_typerror(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("narg="); IDX(L, narg);
  P(", ");
  P("tname="); QS(tname, (size_t)-1);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_luaL_typerror(L, narg, tname);
  bn = 0; P("#%lu < luaL_typerror", seq);
  P(" = %d", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

int tr_luaL_argerror(lua_State *L, int numarg, const char *extramsg) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > luaL_argerror(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("numarg="); IDX(L, numarg);
  P(", ");
  P("extramsg="); QS(extramsg, (size_t)-1);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_luaL_argerror(L, numarg, extramsg);
  bn = 0; P("#%lu < luaL_argerror", seq);
  P(" = %d", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

const char * tr_luaL_checklstring(lua_State *L, int numArg, size_t *l) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > luaL_checklstring(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("numArg="); IDX(L, numArg);
  P(", ");
  P("l=%p", (void*)l);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  const char * rv = p_luaL_checklstring(L, numArg, l);
  bn = 0; P("#%lu < luaL_checklstring", seq);
  P(" = "); QS(rv, (size_t)-1);
  if (l) P(" l=%llu", (unsigned long long)*l);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

const char * tr_luaL_optlstring(lua_State *L, int numArg, const char *def, size_t *l) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > luaL_optlstring(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("numArg="); IDX(L, numArg);
  P(", ");
  P("def="); QS(def, (size_t)-1);
  P(", ");
  P("l=%p", (void*)l);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  const char * rv = p_luaL_optlstring(L, numArg, def, l);
  bn = 0; P("#%lu < luaL_optlstring", seq);
  P(" = "); QS(rv, (size_t)-1);
  if (l) P(" l=%llu", (unsigned long long)*l);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

lua_Number tr_luaL_checknumber(lua_State *L, int numArg) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > luaL_checknumber(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("numArg="); IDX(L, numArg);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  lua_Number rv = p_luaL_checknumber(L, numArg);
  bn = 0; P("#%lu < luaL_checknumber", seq);
  P(" = %.14g", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

lua_Number tr_luaL_optnumber(lua_State *L, int nArg, lua_Number def) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > luaL_optnumber(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("nArg="); IDX(L, nArg);
  P(", ");
  P("def=%.14g", def);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  lua_Number rv = p_luaL_optnumber(L, nArg, def);
  bn = 0; P("#%lu < luaL_optnumber", seq);
  P(" = %.14g", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

lua_Integer tr_luaL_checkinteger(lua_State *L, int numArg) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > luaL_checkinteger(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("numArg="); IDX(L, numArg);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  lua_Integer rv = p_luaL_checkinteger(L, numArg);
  bn = 0; P("#%lu < luaL_checkinteger", seq);
  P(" = %lld", (long long)rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

lua_Integer tr_luaL_optinteger(lua_State *L, int nArg, lua_Integer def) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > luaL_optinteger(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("nArg="); IDX(L, nArg);
  P(", ");
  P("def=%lld", (long long)def);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  lua_Integer rv = p_luaL_optinteger(L, nArg, def);
  bn = 0; P("#%lu < luaL_optinteger", seq);
  P(" = %lld", (long long)rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

void tr_luaL_checkstack(lua_State *L, int sz, const char *msg) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > luaL_checkstack(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("sz=%d", sz);
  P(", ");
  P("msg="); QS(msg, (size_t)-1);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  p_luaL_checkstack(L, sz, msg);
  bn = 0; P("#%lu < luaL_checkstack", seq);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
}

void tr_luaL_checktype(lua_State *L, int narg, int t) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > luaL_checktype(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("narg="); IDX(L, narg);
  P(", ");
  P("t=%d", t);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  p_luaL_checktype(L, narg, t);
  bn = 0; P("#%lu < luaL_checktype", seq);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
}

void tr_luaL_checkany(lua_State *L, int narg) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > luaL_checkany(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("narg="); IDX(L, narg);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  p_luaL_checkany(L, narg);
  bn = 0; P("#%lu < luaL_checkany", seq);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
}

int tr_luaL_newmetatable(lua_State *L, const char *tname) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > luaL_newmetatable(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("tname="); QS(tname, (size_t)-1);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_luaL_newmetatable(L, tname);
  bn = 0; P("#%lu < luaL_newmetatable", seq);
  P(" = %d", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

void * tr_luaL_checkudata(lua_State *L, int ud, const char *tname) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > luaL_checkudata(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("ud="); IDX(L, ud);
  P(", ");
  P("tname="); QS(tname, (size_t)-1);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  void * rv = p_luaL_checkudata(L, ud, tname);
  bn = 0; P("#%lu < luaL_checkudata", seq);
  P(" = %p", (void*)rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

void tr_luaL_where(lua_State *L, int lvl) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > luaL_where(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("lvl=%d", lvl);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  p_luaL_where(L, lvl);
  bn = 0; P("#%lu < luaL_where", seq);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
}

int tr_luaL_checkoption(lua_State *L, int narg, const char *def, const char *const lst[]) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > luaL_checkoption(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("narg="); IDX(L, narg);
  P(", ");
  P("def="); QS(def, (size_t)-1);
  P(", ");
  P("lst="); OPTS(lst);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_luaL_checkoption(L, narg, def, lst);
  bn = 0; P("#%lu < luaL_checkoption", seq);
  P(" = %d", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

int tr_luaL_ref(lua_State *L, int t) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > luaL_ref(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("t="); IDX(L, t);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_luaL_ref(L, t);
  bn = 0; P("#%lu < luaL_ref", seq);
  P(" = %d", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

void tr_luaL_unref(lua_State *L, int t, int ref) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > luaL_unref(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("t="); IDX(L, t);
  P(", ");
  P("ref=%d", ref);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  p_luaL_unref(L, t, ref);
  bn = 0; P("#%lu < luaL_unref", seq);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
}

int tr_luaL_loadfile(lua_State *L, const char *filename) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > luaL_loadfile(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("filename="); QS(filename, (size_t)-1);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_luaL_loadfile(L, filename);
  bn = 0; P("#%lu < luaL_loadfile", seq);
  P(" = %d (%s)", rv, SN(rv)); if (rv != 0 && rv != 1) { P(" err="); IDX(L, -1); }
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

int tr_luaL_loadbuffer(lua_State *L, const char *buff, size_t sz, const char *name) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > luaL_loadbuffer(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("buff="); QS(buff, (size_t)-1);
  P(", ");
  P("sz=%llu", (unsigned long long)sz);
  P(", ");
  P("name="); QS(name, (size_t)-1);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_luaL_loadbuffer(L, buff, sz, name);
  bn = 0; P("#%lu < luaL_loadbuffer", seq);
  P(" = %d (%s)", rv, SN(rv)); if (rv != 0 && rv != 1) { P(" err="); IDX(L, -1); }
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

int tr_luaL_loadstring(lua_State *L, const char *s) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > luaL_loadstring(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("s="); QS(s, (size_t)-1);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_luaL_loadstring(L, s);
  bn = 0; P("#%lu < luaL_loadstring", seq);
  P(" = %d (%s)", rv, SN(rv)); if (rv != 0 && rv != 1) { P(" err="); IDX(L, -1); }
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

lua_State * tr_luaL_newstate(void) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  lua_State *L = NULL;
  (void)L;
  load_core();
  P("#%lu > luaL_newstate(", seq);
  P(")");
  EMIT();
  lua_State * rv = p_luaL_newstate();
  install_hook(rv);
  bn = 0; P("#%lu < luaL_newstate", seq);
  P(" = %p", (void*)rv);
  EMIT();
  return rv;
}

const char * tr_luaL_gsub(lua_State *L, const char *s, const char *p, const char *r) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > luaL_gsub(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("s="); QS(s, (size_t)-1);
  P(", ");
  P("p="); QS(p, (size_t)-1);
  P(", ");
  P("r="); QS(r, (size_t)-1);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  const char * rv = p_luaL_gsub(L, s, p, r);
  bn = 0; P("#%lu < luaL_gsub", seq);
  P(" = "); QS(rv, (size_t)-1);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

const char * tr_luaL_findtable(lua_State *L, int idx, const char *fname, int szhint) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > luaL_findtable(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("idx="); IDX(L, idx);
  P(", ");
  P("fname="); QS(fname, (size_t)-1);
  P(", ");
  P("szhint=%d", szhint);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  const char * rv = p_luaL_findtable(L, idx, fname, szhint);
  bn = 0; P("#%lu < luaL_findtable", seq);
  P(" = "); QS(rv, (size_t)-1);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

void tr_luaL_buffinit(lua_State *L, luaL_Buffer *B) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > luaL_buffinit(", seq);
  P("L=%p", (void*)L);
  P(", ");
  P("B=%p", (void*)B);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  p_luaL_buffinit(L, B);
  bn = 0; P("#%lu < luaL_buffinit", seq);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
}

char * tr_luaL_prepbuffer(luaL_Buffer *B) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  lua_State *L = B->L;
  (void)L;
  load_core();
  P("#%lu > luaL_prepbuffer(", seq);
  P("B=%p", (void*)B);
  P(")");
  EMIT();
  char * rv = p_luaL_prepbuffer(B);
  bn = 0; P("#%lu < luaL_prepbuffer", seq);
  P(" = "); QS(rv, (size_t)-1);
  EMIT();
  return rv;
}

void tr_luaL_addlstring(luaL_Buffer *B, const char *s, size_t l) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  lua_State *L = B->L;
  (void)L;
  load_core();
  P("#%lu > luaL_addlstring(", seq);
  P("B=%p", (void*)B);
  P(", ");
  P("s="); QS(s, (size_t)-1);
  P(", ");
  P("l=%llu", (unsigned long long)l);
  P(")");
  EMIT();
  p_luaL_addlstring(B, s, l);
  bn = 0; P("#%lu < luaL_addlstring", seq);
  EMIT();
}

void tr_luaL_addstring(luaL_Buffer *B, const char *s) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  lua_State *L = B->L;
  (void)L;
  load_core();
  P("#%lu > luaL_addstring(", seq);
  P("B=%p", (void*)B);
  P(", ");
  P("s="); QS(s, (size_t)-1);
  P(")");
  EMIT();
  p_luaL_addstring(B, s);
  bn = 0; P("#%lu < luaL_addstring", seq);
  EMIT();
}

void tr_luaL_addvalue(luaL_Buffer *B) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  lua_State *L = B->L;
  (void)L;
  load_core();
  P("#%lu > luaL_addvalue(", seq);
  P("B=%p", (void*)B);
  P(")");
  EMIT();
  p_luaL_addvalue(B);
  bn = 0; P("#%lu < luaL_addvalue", seq);
  EMIT();
}

void tr_luaL_pushresult(luaL_Buffer *B) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  lua_State *L = B->L;
  (void)L;
  load_core();
  P("#%lu > luaL_pushresult(", seq);
  P("B=%p", (void*)B);
  P(")");
  EMIT();
  p_luaL_pushresult(B);
  bn = 0; P("#%lu < luaL_pushresult", seq);
  P(" -> "); IDX(L, -1); P(" top=%d", p_lua_gettop(L));
  EMIT();
}

int tr_luaopen_base(lua_State *L) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > luaopen_base(", seq);
  P("L=%p", (void*)L);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_luaopen_base(L);
  bn = 0; P("#%lu < luaopen_base", seq);
  P(" = %d", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

int tr_luaopen_table(lua_State *L) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > luaopen_table(", seq);
  P("L=%p", (void*)L);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_luaopen_table(L);
  bn = 0; P("#%lu < luaopen_table", seq);
  P(" = %d", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

int tr_luaopen_io(lua_State *L) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > luaopen_io(", seq);
  P("L=%p", (void*)L);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_luaopen_io(L);
  bn = 0; P("#%lu < luaopen_io", seq);
  P(" = %d", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

int tr_luaopen_os(lua_State *L) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > luaopen_os(", seq);
  P("L=%p", (void*)L);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_luaopen_os(L);
  bn = 0; P("#%lu < luaopen_os", seq);
  P(" = %d", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

int tr_luaopen_string(lua_State *L) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > luaopen_string(", seq);
  P("L=%p", (void*)L);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_luaopen_string(L);
  bn = 0; P("#%lu < luaopen_string", seq);
  P(" = %d", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

int tr_luaopen_math(lua_State *L) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > luaopen_math(", seq);
  P("L=%p", (void*)L);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_luaopen_math(L);
  bn = 0; P("#%lu < luaopen_math", seq);
  P(" = %d", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

int tr_luaopen_debug(lua_State *L) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > luaopen_debug(", seq);
  P("L=%p", (void*)L);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_luaopen_debug(L);
  bn = 0; P("#%lu < luaopen_debug", seq);
  P(" = %d", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

int tr_luaopen_package(lua_State *L) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > luaopen_package(", seq);
  P("L=%p", (void*)L);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  int rv = p_luaopen_package(L);
  bn = 0; P("#%lu < luaopen_package", seq);
  P(" = %d", rv);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  return rv;
}

void tr_luaL_openlibs(lua_State *L) {
  char buf[TRBUF]; int bn = 0; unsigned long seq = ++g_seq;
  (void)L;
  load_core();
  P("#%lu > luaL_openlibs(", seq);
  P("L=%p", (void*)L);
  P(")");
  P(" top=%d", p_lua_gettop(L));
  EMIT();
  p_luaL_openlibs(L);
  bn = 0; P("#%lu < luaL_openlibs", seq);
  P(" top=%d", p_lua_gettop(L));
  EMIT();
}
