local function f(x) if x > 2 then error("boom at "..x) end return f(x+1) end
print(pcall(f, 1))
print(select('#', pcall(error)))
print(pcall(error, {code=1}))
local co = coroutine.create(function(a, b)
  print("co", a, b)
  local c = coroutine.yield(a+b)
  print("co2", c)
  local d, e = coroutine.yield(c*2)
  return d+e
end)
print(coroutine.resume(co, 1, 2))
print(coroutine.resume(co, 10))
print(coroutine.resume(co, 3, 4))
print(coroutine.resume(co))
print(string.format("%5.2f|%s|%q", 3.14159, "x", "a\nb"))
print(("hello"):upper(), #"abc")
local t = setmetatable({}, {__index=function(t,k) return k.."!" end})
print(t.foo)
print(tostring(nil), tonumber("0x10"), tonumber("  12  "))
print(string.rep("ab", 3, ","))
print(table.concat({1,2,3}, "-"))
print(os.time() > 0, type(io.write))
io.write("io ok\n")
print(loadstring("return 1+")) 
local ok, e = pcall(function() local x = nil; return x.y end)
print(ok, e)
print(xpcall(function() error("xp") end, debug.traceback))
